/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes
{
    public class GraspResult : Message
    {
        public const string RosMessageName = "franka_gripper/GraspResult";

        public bool success { get; set; }
        public string error { get; set; }

        public GraspResult()
        {
            this.success = false;
            this.error = "";
        }

        public GraspResult(bool success, string error)
        {
            this.success = success;
            this.error = error;
        }
    }
}
