/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;
using RosSharp.RosBridgeClient.MessageTypes.FrankaEmika;

namespace RosSharp.RosBridgeClient.MessageTypes.FrankaEmika
{
    public class GraspActionResult : Message
    {
        public const string RosMessageName = "franka_gripper/GraspActionResult";

        public Header header { get; set; }
        public GoalStatus status { get; set; }
        public GraspResult result { get; set; }

        public GraspActionResult()
        {
            this.header = new Header();
            this.status = new GoalStatus();
            this.result = new GraspResult();
        }

        public GraspActionResult(Header header, GoalStatus status, GraspResult result)
        {
            this.header = header;
            this.status = status;
            this.result = result;
        }
    }
}
